# CallingViewer by YangHaitao

app_debug: true

# LOG_LEVEL
# a value of (NOSET, DEBUG, INFO, WARNING, ERROR, CRITICAL)
# default NOSET
log_level: INFO

server_host: 127.0.0.1
server_port: 9009

db_type: bsddb

# DATA_PATH
# a path for all data
# data_path: /home/breeze/Develop/CallingViewer/DATA

